---

driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  require_ruby_for_busser: true
  group_vars_path: local
  require_chef_for_busser: false

transport:
  max_ssh_sessions: 6
  connection_retries: 5

busser:
  ruby_bindir: /usr/bin

platforms:

  - name: jessie
    provisioner:
      ansible_version: 2.2.0.0
      require_ansible_omnibus: True
      ansible_omnibus_url: https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh
    driver_config:
      box: debian/jessie64

  - name: trusty
    provisioner:
      ansible_version: 2.2.0.0
      require_ansible_omnibus: True
      ansible_omnibus_url: https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh
    driver_config:
      box: ubuntu/trusty64

  - name: xenial
    provisioner:
      ansible_version: 2.2.0.0
      require_ansible_omnibus: True
      ansible_omnibus_url: https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh
    driver_config:
      box: ubuntu/xenial64

  - name: centos7
    driver_config:
      box: puppetlabs/centos-7.0-64-nocm

  - name: centos6
    driver_config:
      box: centos/6

suites:
  - name: packer
    provisioner:
      hosts: packer
